# SPDX-FileCopyrightText: 2025
#
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"