# SPDX-FileCopyrightText: 2025
# 
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "a2a4k"
SPDX-PackageSupplier = "A2a4k"
SPDX-PackageDownloadLocation = "https://github.com/a2a-4k/a2a-4k"


[[annotations]]
path = ["**/fonts/**",
    "**/assets/**",
    "**/chat/flutter*.js",
    "**/chat/canvaskit/**",
    "gradle/**",
    "gradlew",
    "gradlew.bat"]
precedence = "override"
SPDX-FileCopyrightText = "The original author or authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "**/chat/favicon.png",
    "**/chat/icons/*.png",
    "**/chat/main.dart.wasm",
    "**/chat/main.dart.js",
    "**/chat/main.dart.mjs",
    "**/chat/index.html",
    "**/chat/*.json",
]
precedence = "override"
SPDX-FileCopyrightText = "The original author or authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs-src/docs/**",
    "docs-src/src/**",
    "docs-src/*.json",
    "docs-src/blog/**",
    "docs-src/static/**",
    "docs/**"
]
precedence = "override"
SPDX-FileCopyrightText = "The original author or authors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/.gitignore", ".gitattributes", "**/README.md", "CODEOWNERS", ".editorconfig", "**/main/resources/META-INF/**", "**/test/resources/META-INF/**", "**/jvmMain/resources/META-INF/**", "**/jvmTest/resources/META-INF/**", "**/test/resources/*.json", "**/test/resources/*.txt", "**/test/resources/*.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
