# SPDX-FileCopyrightText: 2025
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [ main ]

jobs:
  CI:
    uses: eclipse-lmos/.github/.github/workflows/gradle-ci-main.yml@main
    permissions:
      contents: write
      packages: write
    secrets:
      oss-username: ${{ secrets.OSSRH_USERNAME }}
      oss-password: ${{ secrets.OSSRH_PASSWORD }}
      signing-key-id: ${{ secrets.GPG_SUBKEY_ID }}
      signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
      signing-key-password: ${{ secrets.GPG_PASSPHRASE }}
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
