# SPDX-FileCopyrightText: 2025
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  CI:
    uses: eclipse-lmos/.github/.github/workflows/gradle-ci.yml@main
    permissions:
      contents: read
