# SPDX-FileCopyrightText: 2025
#
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: What do you want to release?
        options: 
        - Milestone
        - Release

jobs:
  CI:
    uses: eclipse-lmos/.github/.github/workflows/gradle-release-app.yml@main
    permissions:
      contents: write
      packages: write
    secrets:
      oss-username: ${{ secrets.OSSRH_USERNAME }}
      oss-password: ${{ secrets.OSSRH_PASSWORD }}
      bot-app-id: ${{ secrets.COMMITER_APPID }}
      bot-private-key: ${{ secrets.COMMITER_KEY }}
      signing-key-id: ${{ secrets.GPG_SUBKEY_ID }}
      signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
      signing-key-password: ${{ secrets.GPG_PASSPHRASE }}
    with:
      release-type: ${{ github.event.inputs.release-type }}